export const robots = [
  {
    id: 1,
    name: "Cordey Greenard",
    username: "Gwenaëlle",
    email: "cgreenard0@gov.uk",
  },
  {
    id: 2,
    name: "Ingmar Androletti",
    username: "Clémence",
    email: "iandroletti1@google.com.au",
  },
  { id: 3, name: "Brinn Usmar", username: "Åslög", email: "busmar2@blog.com" },
  {
    id: 4,
    name: "Mile Masham",
    username: "Inès",
    email: "mmasham3@storify.com",
  },
  { id: 5, name: "Vivian Duffan", username: "Loïs", email: "vduffan4@t.co" },
  {
    id: 6,
    name: "Octavia Smaile",
    username: "Örjan",
    email: "osmaile5@odnoklassniki.ru",
  },
  { id: 7, name: "Annice Jost", username: "Ruì", email: "ajost6@cornell.edu" },
  {
    id: 8,
    name: "Levy Hickenbottom",
    username: "Östen",
    email: "lhickenbottom7@microsoft.com",
  },
  {
    id: 9,
    name: "Brendin Shepherdson",
    username: "Félicie",
    email: "bshepherdson8@cafepress.com",
  },
  {
    id: 10,
    name: "Andriette Yeoland",
    username: "Géraldine",
    email: "ayeoland9@histats.com",
  },
  {
    id: 11,
    name: "Kirbee Tidey",
    username: "Lea",
    email: "ktideya@people.com.cn",
  },
  {
    id: 12,
    name: "Jessie Matthaus",
    username: "Bérangère",
    email: "jmatthausb@ow.ly",
  },
  {
    id: 13,
    name: "Efren Cayet",
    username: "Publicité",
    email: "ecayetc@cam.ac.uk",
  },
  { id: 14, name: "Winonah Chadd", username: "Cloé", email: "wchaddd@msu.edu" },
  // {
  //   id: 15,
  //   name: "Bear Rouse",
  //   username: "Angèle",
  //   email: "brousee@state.tx.us",
  // },
  // {
  //   id: 16,
  //   name: 'Florie Velden',
  //   username: 'Valérie',
  //   email: 'fveldenf@alexa.com',
  // },
  // {
  //   id: 17,
  //   name: 'Guglielma McIlraith',
  //   username: 'Yè',
  //   email: 'gmcilraithg@howstuffworks.com',
  // },
  // {
  //   id: 18,
  //   name: 'Joshuah Gallon',
  //   username: 'Tú',
  //   email: 'jgallonh@marketwatch.com',
  // },
  // {
  //   id: 19,
  //   name: 'Cort Abelov',
  //   username: 'Josée',
  //   email: 'cabelovi@discovery.com',
  // },
  // {
  //   id: 20,
  //   name: 'Dudley Battany',
  //   username: 'Yú',
  //   email: 'dbattanyj@fda.gov',
  // },
  // {
  //   id: 21,
  //   name: 'Dudley Battany',
  //   username: 'Yú',
  //   email: 'dbattanyj@fda.gov',
  // },
];
